apiVersion: v1
kind: Secret
metadata:
    name: secret-db
    namespace: postgre-app
type: Opaque
data:
    PGDB_PASSWORD: ENC[AES256_GCM,data:w8odrxdSlj/O882V,iv:9Ii8Qd4Ed63x6vmSF5MDW5L5a7hVQ7PjVlpsXIsjN+4=,tag:e5YSMf8SyrnDGGHttOqwFw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:joCj9nR2lJFrSc3F,iv:3q7dUD7IM6tx7lGkVpLxWhI1/xST8GN7XQZDYynW2qo=,tag:a7s8CnRsP1+dyfuj1V7mTw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/python-project-cluster/locations/northamerica-northeast2/keyRings/key/cryptoKeys/key
          created_at: "2024-11-19T16:22:49Z"
          enc: CiQAbVvpSB87Y1SzgxQE821gqk+Pobv1hVNDTYqd3WDEgd+S1VYSSQA4Nizq9Mg+u/hVfiwruxHkrhOK96jpgqlBEuzbjkSwkYlaN1mgXTS6Tik5hHcJvqX0OyEdinF5bBwapBSz+HmcVuK1oDopKM4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-19T16:22:51Z"
    mac: ENC[AES256_GCM,data:rg+PhW5Rsi9z8UpL0pJ5/y82uAAa0GKy/sMeKQ8VTxQ4hPqajCyspxDcYAviIlXngkcOIuC0AZPn6AnWOR3BAIWVLndGfI0m3gh32MoVezPWD1fu3qod3Tk7106SFX+WpNap/j2XcCWbF5TDEr6pFlHuInJt+8FdpNAbT+TbIyo=,iv:TfXSxkYhTGIglQRWYE5MpvyMal3MoOz8L6YqjDYjLVA=,tag:20Xp9KEBnCnpjeJ18app/g==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
